spring:
  application:
    name: streammq-sample-dlq

streammq:
  enabled: true
  namespace: dlq
  producer:
    group: dlq-producer-group
  retry:
    max-reconsume-times: 3

redisson:
  singleServerConfig:
    address: "redis://127.0.0.1:6379"
    database: 0