spring:
  application:
    name: streammq-sample-interceptor

streammq:
  enabled: true
  namespace: interceptor
  producer:
    group: interceptor-producer-group

redisson:
  singleServerConfig:
    address: "redis://127.0.0.1:6379"
    database: 0